import { ApiError, apiRequest } from "@/lib/api-client"
import { isPartnerSubscriptionListResponse, isPartnerSubscriptionResponse, isSubscriptionPlanListResponse, isSubscriptionPlanResponse, type PartnerSubscriptionFilters, type PartnerSubscriptionInput, type PartnerSubscriptionListResponse, type PartnerSubscriptionRecord, type RenewSubscriptionInput, type SubscriptionPlanFilters, type SubscriptionPlanInput, type SubscriptionPlanListResponse, type SubscriptionPlanRecord } from "./subscription.types"

function path(base: string, filters: object): string { const params = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value !== undefined && value !== "") params.set(key, String(value)); const query = params.toString(); return query ? `${base}?${query}` : base }
function parsePlan(payload: unknown): SubscriptionPlanRecord { if (!isSubscriptionPlanResponse(payload)) throw new ApiError("Format response Subscription Plan tidak sesuai.", 500); return payload.data }
function parseSubscription(payload: unknown): PartnerSubscriptionRecord { if (!isPartnerSubscriptionResponse(payload)) throw new ApiError("Format response Partner Subscription tidak sesuai.", 500); return payload.data }
export async function getSubscriptionPlans(token: string, filters: SubscriptionPlanFilters = {}, signal?: AbortSignal): Promise<SubscriptionPlanListResponse> { const payload = await apiRequest(path("/v1/subscription-plans", filters), { signal }, token); if (!isSubscriptionPlanListResponse(payload)) throw new ApiError("Format response daftar Subscription Plan tidak sesuai.", 500); return payload }
export async function createSubscriptionPlan(token: string, input: SubscriptionPlanInput): Promise<SubscriptionPlanRecord> { return parsePlan(await apiRequest("/v1/subscription-plans", { method: "POST", body: JSON.stringify(input) }, token)) }
export async function updateSubscriptionPlan(token: string, id: number, input: SubscriptionPlanInput): Promise<SubscriptionPlanRecord> { return parsePlan(await apiRequest(`/v1/subscription-plans/${id}`, { method: "PUT", body: JSON.stringify(input) }, token)) }
export async function deleteSubscriptionPlan(token: string, id: number): Promise<void> { await apiRequest(`/v1/subscription-plans/${id}`, { method: "DELETE" }, token) }
export async function getPartnerSubscriptions(token: string, filters: PartnerSubscriptionFilters = {}, signal?: AbortSignal): Promise<PartnerSubscriptionListResponse> { const payload = await apiRequest(path("/v1/partner-subscriptions", filters), { signal }, token); if (!isPartnerSubscriptionListResponse(payload)) throw new ApiError("Format response daftar Partner Subscription tidak sesuai.", 500); return payload }
export async function createPartnerSubscription(token: string, input: PartnerSubscriptionInput): Promise<PartnerSubscriptionRecord> { return parseSubscription(await apiRequest("/v1/partner-subscriptions", { method: "POST", body: JSON.stringify(input) }, token)) }
export async function activatePartnerSubscription(token: string, id: number): Promise<PartnerSubscriptionRecord> { return parseSubscription(await apiRequest(`/v1/partner-subscriptions/${id}/activate`, { method: "POST" }, token)) }
export async function renewPartnerSubscription(token: string, id: number, input: RenewSubscriptionInput): Promise<PartnerSubscriptionRecord> { return parseSubscription(await apiRequest(`/v1/partner-subscriptions/${id}/renew`, { method: "POST", body: JSON.stringify(input) }, token)) }
export async function cancelPartnerSubscription(token: string, id: number): Promise<PartnerSubscriptionRecord> { return parseSubscription(await apiRequest(`/v1/partner-subscriptions/${id}/cancel`, { method: "POST" }, token)) }
export async function expirePartnerSubscription(token: string, id: number): Promise<PartnerSubscriptionRecord> { return parseSubscription(await apiRequest(`/v1/partner-subscriptions/${id}/expire`, { method: "POST" }, token)) }
