import { LoaderCircle } from "lucide-react"
import { useState, type FormEvent, type ReactElement } from "react"

import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useAuth } from "@/features/auth/auth-context"
import { issueVoucher } from "@/features/vouchers/voucher-service"
import type { VoucherPackageRecord, VoucherRecord } from "@/features/vouchers/voucher.types"
import { ApiError } from "@/lib/api-client"

export function VoucherIssueDialog({ partnerId, packages, open, onOpenChange, onIssued, onUnauthorized, onForbidden }: { readonly partnerId: number; readonly packages: ReadonlyArray<VoucherPackageRecord>; readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly onIssued: (vouchers: ReadonlyArray<VoucherRecord>) => void; readonly onUnauthorized: () => void; readonly onForbidden: () => void }): ReactElement {
  const { token } = useAuth(); const [packageId, setPackageId] = useState(""); const [code, setCode] = useState(""); const [expiredAt, setExpiredAt] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState("")
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!token || pending || !packageId) return; setPending(true); setError(""); try { const issued = await issueVoucher(token, { partner_id: partnerId, voucher_package_id: Number(packageId), code: code.trim() ? code.trim().toUpperCase() : undefined, idempotency_key: crypto.randomUUID(), expired_at: expiredAt ? new Date(expiredAt).toISOString() : undefined }); onIssued([issued]); onOpenChange(false); setCode(""); setExpiredAt("") } catch (caught: unknown) { if (caught instanceof ApiError && caught.status === 401) return onUnauthorized(); if (caught instanceof ApiError && caught.status === 403) return onForbidden(); setError(caught instanceof ApiError ? Object.values(caught.validationErrors).flat()[0] ?? caught.message : "Tidak dapat terhubung ke server.") } finally { setPending(false) } }
  const activePackages = packages.filter((item) => item.is_active)
  return <Dialog open={open} onOpenChange={(next) => !pending && onOpenChange(next)}><DialogContent><DialogHeader><DialogTitle>Terbitkan Voucher</DialogTitle><DialogDescription>Setiap penerbitan memakai idempotency key unik agar aman diulang.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={(event) => void submit(event)}><div className="grid gap-2"><Label htmlFor="issue-package">Voucher Package</Label><Select value={packageId} onValueChange={(value) => value && setPackageId(value)}><SelectTrigger id="issue-package"><SelectValue placeholder="Pilih package" /></SelectTrigger><SelectContent>{activePackages.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name} · {new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(item.price)}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label htmlFor="issue-code">Kode (opsional)</Label><Input id="issue-code" value={code} maxLength={50} onChange={(event) => setCode(event.target.value)} placeholder="Otomatis jika kosong" /></div><div className="grid gap-2"><Label htmlFor="issue-expired">Kedaluwarsa (opsional)</Label><Input id="issue-expired" type="datetime-local" value={expiredAt} onChange={(event) => setExpiredAt(event.target.value)} /></div>{error && <p className="text-sm text-destructive" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" disabled={pending} onClick={() => onOpenChange(false)}>Batal</Button><Button type="submit" disabled={pending || activePackages.length === 0 || !packageId}>{pending && <LoaderCircle className="animate-spin" aria-hidden="true" />}Terbitkan</Button></DialogFooter></form></DialogContent></Dialog>
}
